// AUTO-GENERATED — do not edit by hand.
// Remix Icon set (Apache-2.0) imported as React components via SVGR.
// Each icon uses fill="currentColor", so colour follows the theme.

export { default as RiAlertFill } from './svg/alert-fill.svg?react'
export { default as RiArrowLeftDoubleLine } from './svg/arrow-left-double-line.svg?react'
export { default as RiArrowLeftSLine } from './svg/arrow-left-s-line.svg?react'
export { default as RiArrowRightDoubleLine } from './svg/arrow-right-double-line.svg?react'
export { default as RiArrowRightSLine } from './svg/arrow-right-s-line.svg?react'
export { default as RiCheckLine } from './svg/check-line.svg?react'
export { default as RiCheckboxCircleFill } from './svg/checkbox-circle-fill.svg?react'
export { default as RiCloseLine } from './svg/close-line.svg?react'
export { default as RiDeleteBinLine } from './svg/delete-bin-line.svg?react'
export { default as RiDownloadLine } from './svg/download-line.svg?react'
export { default as RiEditLine } from './svg/edit-line.svg?react'
export { default as RiErrorWarningFill } from './svg/error-warning-fill.svg?react'
export { default as RiEyeLine } from './svg/eye-line.svg?react'
export { default as RiFireFill } from './svg/fire-fill.svg?react'
export { default as RiFlashlightFill } from './svg/flashlight-fill.svg?react'
export { default as RiGlobalLine } from './svg/global-line.svg?react'
export { default as RiHeartLine } from './svg/heart-line.svg?react'
export { default as RiHome5Line } from './svg/home-5-line.svg?react'
export { default as RiInformationFill } from './svg/information-fill.svg?react'
export { default as RiLinksLine } from './svg/links-line.svg?react'
export { default as RiLockLine } from './svg/lock-line.svg?react'
export { default as RiMagicFill } from './svg/magic-fill.svg?react'
export { default as RiMailLine } from './svg/mail-line.svg?react'
export { default as RiNotification3Line } from './svg/notification-3-line.svg?react'
export { default as RiRocketFill } from './svg/rocket-fill.svg?react'
export { default as RiSearchLine } from './svg/search-line.svg?react'
export { default as RiSettings3Line } from './svg/settings-3-line.svg?react'
export { default as RiShieldCheckLine } from './svg/shield-check-line.svg?react'
export { default as RiStarLine } from './svg/star-line.svg?react'
export { default as RiThumbUpFill } from './svg/thumb-up-fill.svg?react'
export { default as RiTimeLine } from './svg/time-line.svg?react'
export { default as RiUploadLine } from './svg/upload-line.svg?react'
export { default as RiUser3Line } from './svg/user-3-line.svg?react'
